version: '3.8'

services:
  # Key-Value Storage Service
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: key-value-storage
    ports:
      - "6969:6969"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=6969
      - DEBUG=True
      - DB_URL=sqlite+aiosqlite:///test.db
      - TLL_DEFAULT=30
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped


  # Mock Client for Testing
  mock-client:
    build:
      context: ./mock_client
      dockerfile: Dockerfile
    container_name: key-value-storage-client
    depends_on:
      - service
    environment:
      - API_URL=http://service:6969
    restart: on-failure
